apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rw48-qrbt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rw48-qrbt-java-quarkus-gitops